"""initial schema

Revision ID: 657ecae8ddab
Revises: 
Create Date: 2026-07-19 09:05:34.472792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '657ecae8ddab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_sources',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.Enum('STREAMING', 'SOCIAL', 'EMAIL', 'ADVERTISING', 'SALES', 'OTHER', name='analyticssourcetype', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('artists',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backup_records',
    sa.Column('backup_type', sa.Enum('MANUAL', 'SCHEDULED', 'PRE_RESTORE', name='backuptype', native_enum=False), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_rules',
    sa.Column('release_type', sa.Enum('STREAMING_SINGLE', 'EP', 'ALBUM', 'INSTRUMENTAL', 'REMIX', 'CLIENT_DELIVERY', 'BEAT_LICENSE', 'SYNC_PITCH', 'SOCIAL_ONLY', name='releasetype', native_enum=False), nullable=True),
    sa.Column('category', sa.Enum('AUDIO', 'METADATA', 'RIGHTS', 'MARKETING', name='checklistcategory', native_enum=False), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('severity', sa.Enum('BLOCKING', 'RECOMMENDED', 'WARNING', name='checklistseverity', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('delivery_presets',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('preset_type', sa.Enum('CLIENT', 'SYNC', 'DISTRIBUTOR', name='deliverypresettype', native_enum=False), nullable=False),
    sa.Column('required_asset_types', sa.JSON(), nullable=False),
    sa.Column('is_system_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scanner_roots',
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('scanner_runs',
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='scannerrunstatus', native_enum=False), nullable=False),
    sa.Column('scanned_roots', sa.JSON(), nullable=False),
    sa.Column('files_scanned', sa.Integer(), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.Enum('MANUAL', 'SCHEDULED', name='scannertrigger', native_enum=False), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_tag_name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('paired_devices',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REVOKED', 'EXPIRED', name='devicestatus', native_enum=False), nullable=False),
    sa.Column('pairing_code_hash', sa.String(length=256), nullable=True),
    sa.Column('pairing_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_token_hash', sa.String(length=256), nullable=True),
    sa.Column('session_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_ip', sa.String(length=64), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('internal_code', sa.String(length=32), nullable=False),
    sa.Column('working_title', sa.String(length=300), nullable=False),
    sa.Column('final_title', sa.String(length=300), nullable=True),
    sa.Column('artist_id', sa.Uuid(), nullable=True),
    sa.Column('producer_name', sa.String(length=200), nullable=True),
    sa.Column('featured_artists', sa.JSON(), nullable=False),
    sa.Column('alternate_titles', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bpm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('musical_key', sa.String(length=16), nullable=True),
    sa.Column('time_signature', sa.String(length=8), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('subgenre', sa.String(length=100), nullable=True),
    sa.Column('mood', sa.String(length=100), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('instruments', sa.JSON(), nullable=False),
    sa.Column('vocal_style', sa.String(length=200), nullable=True),
    sa.Column('similar_artists', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('IDEA', 'ARRANGEMENT', 'PRODUCTION', 'VOCALS', 'EDITING', 'MIX', 'MASTER', 'RELEASE_READY', 'SCHEDULED', 'RELEASED', 'ON_HOLD', 'ARCHIVED', name='projectstate', native_enum=False), nullable=False),
    sa.Column('fl_project_path', sa.String(length=1024), nullable=True),
    sa.Column('fl_project_zip_path', sa.String(length=1024), nullable=True),
    sa.Column('project_root_path', sa.String(length=1024), nullable=True),
    sa.Column('current_mix_asset_version_id', sa.Uuid(), nullable=True),
    sa.Column('current_master_asset_version_id', sa.Uuid(), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('revision_notes', sa.Text(), nullable=True),
    sa.Column('split_confirmed', sa.Boolean(), nullable=False),
    sa.Column('sample_clearance_status', sa.Enum('UNRESOLVED', 'CLEARED', 'DENIED', 'NOT_APPLICABLE', name='clearancestatus', native_enum=False), nullable=False),
    sa.Column('one_stop_clearance_status', sa.Enum('UNRESOLVED', 'CLEARED', 'DENIED', 'NOT_APPLICABLE', name='clearancestatus', native_enum=False), nullable=False),
    sa.Column('pro_registration_status', sa.Enum('NOT_REGISTERED', 'PENDING', 'REGISTERED', 'NOT_APPLICABLE', name='proregistrationstatus', native_enum=False), nullable=False),
    sa.Column('master_owner', sa.String(length=200), nullable=True),
    sa.Column('composition_owner', sa.String(length=200), nullable=True),
    sa.Column('release_type', sa.Enum('STREAMING_SINGLE', 'EP', 'ALBUM', 'INSTRUMENTAL', 'REMIX', 'CLIENT_DELIVERY', 'BEAT_LICENSE', 'SYNC_PITCH', 'SOCIAL_ONLY', name='releasetype', native_enum=False), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('distributor', sa.String(length=200), nullable=True),
    sa.Column('isrc', sa.String(length=32), nullable=True),
    sa.Column('upc', sa.String(length=32), nullable=True),
    sa.Column('explicit_status', sa.Enum('NOT_SET', 'EXPLICIT', 'CLEAN', name='explicitstatus', native_enum=False), nullable=False),
    sa.Column('artwork_asset_version_id', sa.Uuid(), nullable=True),
    sa.Column('release_description', sa.Text(), nullable=True),
    sa.Column('release_readiness_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_code', name='uq_project_internal_code')
    )
    op.create_table('audit_events',
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['paired_devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clearances',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('clearance_type', sa.Enum('SAMPLE', 'ONE_STOP', 'INTERPOLATION', 'OTHER', name='clearancetype', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('UNRESOLVED', 'CLEARED', 'DENIED', 'NOT_APPLICABLE', name='clearancestatus', native_enum=False), nullable=False),
    sa.Column('rights_holder_contact', sa.String(length=300), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contributors',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('WRITER', 'PRODUCER', 'PERFORMER', 'PUBLISHER', 'ENGINEER', 'FEATURED_ARTIST', 'OTHER', name='contributorrole', native_enum=False), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('pro_affiliation', sa.String(length=100), nullable=True),
    sa.Column('ipi_number', sa.String(length=32), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_packages',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('preset_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'DRY_RUN', 'PENDING_APPROVAL', 'APPROVED', 'COMPLETED', 'FAILED', name='deliverypackagestatus', native_enum=False), nullable=False),
    sa.Column('output_directory', sa.String(length=1024), nullable=True),
    sa.Column('manifest_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['preset_id'], ['delivery_presets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketing_campaigns',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('artist_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('campaign_type', sa.Enum('FOUR_WEEK', 'SIX_WEEK', 'POST_RELEASE', 'CUSTOM', name='campaigntype', native_enum=False), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='campaignstatus', native_enum=False), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_tags',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'tag_id', name='uq_project_tag')
    )
    op.create_table('project_versions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fl_project_asset_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_scan', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('releases',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('release_type', sa.Enum('STREAMING_SINGLE', 'EP', 'ALBUM', 'INSTRUMENTAL', 'REMIX', 'CLIENT_DELIVERY', 'BEAT_LICENSE', 'SYNC_PITCH', 'SOCIAL_ONLY', name='releasetype', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('distributor', sa.String(length=200), nullable=True),
    sa.Column('isrc', sa.String(length=32), nullable=True),
    sa.Column('upc', sa.String(length=32), nullable=True),
    sa.Column('explicit_status', sa.Enum('NOT_SET', 'EXPLICIT', 'CLEAN', name='explicitstatus', native_enum=False), nullable=False),
    sa.Column('artwork_asset_version_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'RELEASED', name='releasestatus', native_enum=False), nullable=False),
    sa.Column('readiness_status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('isrc', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_imports',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('reporting_period_start', sa.Date(), nullable=False),
    sa.Column('reporting_period_end', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('raw_or_calculated', sa.Enum('RAW', 'CALCULATED', name='raworcalculated', native_enum=False), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_by', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_campaigns.id'], ),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['analytics_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=True),
    sa.Column('asset_type', sa.Enum('FL_PROJECT', 'FL_PROJECT_ZIP', 'MIX', 'MASTER', 'INSTRUMENTAL', 'ACAPELLA', 'CLEAN_VERSION', 'NO_DRUMS', 'NO_VOCALS', 'STEMS', 'ARTWORK', 'LYRICS', 'DOCUMENT', 'VIDEO', 'OTHER', name='assettype', native_enum=False), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_results',
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'WARNING', 'WAIVED', 'BLOCKING', name='checkliststatus', native_enum=False), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('waived_by', sa.Uuid(), nullable=True),
    sa.Column('waived_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['checklist_rules.id'], ),
    sa.ForeignKeyConstraint(['waived_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_assets',
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.Enum('SHORT_VIDEO', 'IMAGE', 'CAROUSEL', 'STORY', 'OTHER', name='contentassettype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('IDEA', 'DRAFTED', 'READY', 'ARCHIVED', name='contentassetstatus', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_campaigns.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deadlines',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('artist_id', sa.Uuid(), nullable=True),
    sa.Column('deadline_type', sa.Enum('ARRANGEMENT_COMPLETE', 'RECORDING', 'MIX_DELIVERY', 'MIX_APPROVAL', 'MASTER_DELIVERY', 'MASTER_APPROVAL', 'ARTWORK', 'DISTRIBUTOR_SUBMISSION', 'PLAYLIST_PITCH', 'CONTENT_CREATION', 'RELEASE', 'POST_RELEASE_CONTENT', 'REMIX', 'CLIENT_DELIVERY', name='deadlinetype', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_campaigns.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketing_drafts',
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('draft_type', sa.Enum('RELEASE_ANNOUNCEMENT', 'INSTAGRAM_CAPTION', 'TIKTOK_CAPTION', 'YOUTUBE_DESCRIPTION', 'SHORT_VIDEO_HOOK', 'BEHIND_THE_SCENES', 'PRODUCTION_BREAKDOWN', 'EMAIL_ANNOUNCEMENT', 'CREATOR_OUTREACH', 'DJ_OUTREACH', 'PLAYLIST_OUTREACH', 'SYNC_PITCH', 'PRESS_RELEASE_OUTLINE', 'FOUR_WEEK_CAMPAIGN', 'SIX_WEEK_CAMPAIGN', 'POST_RELEASE_CAMPAIGN', name='marketingdrafttype', native_enum=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'EDITED', 'ARCHIVED', name='draftstatus', native_enum=False), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('template_version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_campaigns.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rights_shares',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('contributor_id', sa.Uuid(), nullable=True),
    sa.Column('holder_name', sa.String(length=200), nullable=False),
    sa.Column('share_type', sa.Enum('MASTER', 'COMPOSITION', name='rightssharetype', native_enum=False), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_metrics',
    sa.Column('import_id', sa.Uuid(), nullable=False),
    sa.Column('metric_type', sa.Enum('STREAMS', 'LISTENERS', 'SAVES', 'FOLLOWERS', 'PLAYLIST_ADDITIONS', 'VIDEO_VIEWS', 'WATCH_TIME', 'LIKES', 'SHARES', 'COMMENTS', 'LINK_CLICKS', 'EMAIL_SIGNUPS', 'ADVERTISING_SPEND', 'REVENUE', 'BEAT_SALES', 'LICENSING_REVENUE', 'SYNC_INQUIRIES', name='analyticsmetrictype', native_enum=False), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('content_reference', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['analytics_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_versions',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('full_path', sa.String(length=2048), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parsed_artist', sa.String(length=200), nullable=True),
    sa.Column('parsed_track', sa.String(length=300), nullable=True),
    sa.Column('parsed_mix_or_master', sa.String(length=20), nullable=True),
    sa.Column('parsed_version_label', sa.String(length=50), nullable=True),
    sa.Column('parsed_date', sa.Date(), nullable=True),
    sa.Column('parsed_bpm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('parsed_key', sa.String(length=16), nullable=True),
    sa.Column('parsed_metadata', sa.JSON(), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus', native_enum=False), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('registered_via', sa.Enum('MANUAL', 'SCANNER', name='assetregisteredvia', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_versions_content_hash'), ['content_hash'], unique=False)

    op.create_table('audio_analyses',
    sa.Column('asset_version_id', sa.Uuid(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('embedded_title', sa.String(length=300), nullable=True),
    sa.Column('embedded_artist', sa.String(length=200), nullable=True),
    sa.Column('embedded_album', sa.String(length=300), nullable=True),
    sa.Column('embedded_track_number', sa.String(length=20), nullable=True),
    sa.Column('integrated_loudness_lufs', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('loudness_range_lu', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('true_peak_dbfs', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('peak_level_dbfs', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('codec_info', sa.String(length=200), nullable=True),
    sa.Column('ffmpeg_used', sa.Boolean(), nullable=False),
    sa.Column('confirmed_bpm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('confirmed_key', sa.String(length=16), nullable=True),
    sa.Column('bpm_source', sa.Enum('USER_CONFIRMED', 'EMBEDDED', 'MEASURED', 'ESTIMATED', name='metadataconfidence', native_enum=False), nullable=True),
    sa.Column('key_source', sa.Enum('USER_CONFIRMED', 'EMBEDDED', 'MEASURED', 'ESTIMATED', name='metadataconfidence', native_enum=False), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_version_id'], ['asset_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_version_id')
    )
    op.create_table('delivery_manifest_items',
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('asset_version_id', sa.Uuid(), nullable=True),
    sa.Column('role_in_package', sa.String(length=200), nullable=False),
    sa.Column('source_path', sa.String(length=2048), nullable=False),
    sa.Column('destination_relative_path', sa.String(length=1024), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('copied', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_version_id'], ['asset_versions.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['delivery_packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scanner_findings',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('finding_type', sa.Enum('NEW_FILE', 'CHANGED_FILE', 'MISSING_FILE', 'EXACT_DUPLICATE', 'POSSIBLE_DUPLICATE', 'NEW_PROJECT_VERSION', 'NEW_MIX_VERSION', 'NEW_MASTER_VERSION', 'UNEXPECTED_FILE', 'INVALID_PATH', 'OUTSIDE_ROOT', 'LOCKED_FILE', name='findingtype', native_enum=False), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('related_asset_version_id', sa.Uuid(), nullable=True),
    sa.Column('duplicate_of_path', sa.String(length=2048), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'APPROVED', 'REJECTED', 'IGNORED', name='findingstatus', native_enum=False), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['related_asset_version_id'], ['asset_versions.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['scanner_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approved_file_operations',
    sa.Column('finding_id', sa.Uuid(), nullable=True),
    sa.Column('operation_type', sa.Enum('RENAME', 'MOVE', 'DELETE', 'COPY', 'REPLACE', name='fileoperationtype', native_enum=False), nullable=False),
    sa.Column('source_path', sa.String(length=2048), nullable=False),
    sa.Column('destination_path', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'EXECUTED', 'FAILED', 'CANCELLED', name='fileoperationstatus', native_enum=False), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['scanner_findings.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approved_file_operations')
    op.drop_table('scanner_findings')
    op.drop_table('delivery_manifest_items')
    op.drop_table('audio_analyses')
    with op.batch_alter_table('asset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_versions_content_hash'))

    op.drop_table('asset_versions')
    op.drop_table('analytics_metrics')
    op.drop_table('rights_shares')
    op.drop_table('marketing_drafts')
    op.drop_table('deadlines')
    op.drop_table('content_assets')
    op.drop_table('checklist_results')
    op.drop_table('assets')
    op.drop_table('analytics_imports')
    op.drop_table('tracks')
    op.drop_table('releases')
    op.drop_table('project_versions')
    op.drop_table('project_tags')
    op.drop_table('marketing_campaigns')
    op.drop_table('delivery_packages')
    op.drop_table('contributors')
    op.drop_table('clearances')
    op.drop_table('audit_events')
    op.drop_table('projects')
    op.drop_table('paired_devices')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('scanner_runs')
    op.drop_table('scanner_roots')
    op.drop_table('delivery_presets')
    op.drop_table('checklist_rules')
    op.drop_table('backup_records')
    op.drop_table('artists')
    op.drop_table('app_settings')
    op.drop_table('analytics_sources')
    # ### end Alembic commands ###
